#!/bin/bash
# This handy script helps you to create and run a WordPress Docker container
# Version: 3.3
# Author: Eugenio Petulla'
# Author url: https://skillsandmore.org

echo Welcome to the WordPress Docker Local Environment setup widzard

read -p 'Project Name: ' PROJECT_NAME
read -p 'Project Slug: ' PROJECT_SLUG

#while [[ "$ENABLE_PHP_MY_ADMIN" != "y" && "$ENABLE_PHP_MY_ADMIN" != "n" ]]; do
#    read -p 'Enable PHPMyAdmin (y/n): ' ENABLE_PHP_MY_ADMIN
#done

while [[ "$ENABLE_WORDMOVE" != "y" && "$ENABLE_WORDMOVE" != "n" ]]; do
    read -p 'Enable WordMove (y/n): ' ENABLE_WORDMOVE
done

if [ "$ENABLE_WORDMOVE" == "y" ]; then
	WORDMOVE="wordmove:
    tty: true
    depends_on:
      - wordpress
    links:
      - mariadb:mysql
    image: welaika/wordmove:php7
    restart: unless-stopped
    volumes:
      - ./public:/html
      - ~/.ssh:/root/.ssh
    networks:
      - wordpress_$PROJECT_NAME"
fi

mkdir "projects/$PROJECT_NAME" && cd "projects/$PROJECT_NAME" && touch docker-compose.yml
mkdir "var" && cd "var" && mkdir "php" && mkdir "sql"

cd "sql" && touch init.sql
echo "CREATE DATABASE IF NOT EXISTS wordpress;
      USE wordpress;" > init.sql

cd .. && cd ..

cat > .env <<EOL
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=wordpress
DB_USERNAME=root
DB_PASSWORD=hutoltalRWy0kq
UID=1001
GID=1001
EOL

# Copy php files configuration
cp -R ../../var/php/. var/php/

# Copy sql files configuration
cp -R ../../var/sql/. var/sql/

# Copy docker files configuration
cp -R ../../var/docker/. .

# Copy docker files configuration
cp -R ../../var/wp/. ./public/

sed -i "s/NETWORK_NAME/$PROJECT_SLUG/g" ./docker-compose.yml
sed -i "s/CONTAINER_NAME/$PROJECT_NAME_wordpress_1/g" ./makefile

docker-compose build && docker-compose up -d && cd public && sleep 10; composer install

if [ "$ENABLE_WORDMOVE" == "y" ]; then
  touch public/movefile.yml

  cat > public/movefile.yml <<EOL
  global:
    sql_adapter: "wpcli"

  local:
    vhost: "http://0.0.0.0:8080"
    wordpress_path: "<%= ENV['WORDMOVE_WORKDIR'] %>"
    database:
      name: "wordpress"
      user: "root"
      password: "$MYSQL_PASS"
      host: "mariadb"
      charset: "utf8"

  production:
    vhost: "<your_domain_name>"
    wordpress_path: "<absolute_path_to_wp_installation>"

    database:
        name: "<db_name>"
        user: "<username>"
        password: "<password>"
        host: "localhost"
        charset: "utf8"
    ssh:
        host: "<hostname>"
        user: "<user>"
  #      password: "<password>"
  # password is optional, will use public keys if available.
EOL
fi